FROM maven: 3.9.8-jdk-8 AS build

COPY src /app/src
COPY pom.xml /app

WORKDIR /app
RUN mvn clean install

FROM openjdk:8-jre-alpine

// -> ARRUMAR ESSA LINHA COPY -- from=build /app/target/springboot

WORKDIR /APP

EXPOSE 8080

CMD ["java" "-jar", "app.jar" ]

